batmor/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

admin.AdminSite.site_header = 'Batmor Administration'
admin.AdminSite.site_title = 'Batmor Admin'

urlpatterns = [
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('/core/img/favicon.ico'))),
    path('', admin.site.urls),
    path('dashboard/', include('reporting_management.urls')),
]

reporting_management/urls.py
from django.urls import path

from reporting_management import views
from reporting_management.views import OrderReportListView,OrderReportDetailView

app_name = 'reporting_management'
urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('reports/orders/general/', OrderReportListView.as_view(), name='order-report-list'),
    path('reports/orders/general/<int:pk>/', OrderReportDetailView.as_view(), name='order-report-detail'),
]

reporting_management/models.py
from django.db import models
from django.utils import timezone

from core.models import BaseModel


class OrderReport(BaseModel):
    order = models.OneToOneField('admin_management.Order', on_delete=models.SET_NULL, null=True,
                                 related_name='order_report')
    item = models.CharField(max_length=100, null=True, blank=True)
    client = models.CharField(max_length=200, null=True, blank=True)
    quantity = models.FloatField(default=0, null=True, blank=True)
    unit = models.CharField(max_length=5, null=True, blank=True)
    delivery_date = models.DateField(default=timezone.now, null=True, blank=True)
    fulfilled = models.CharField(max_length=10, null=True, blank=True)
    payment_status = models.CharField(max_length=7, null=True, blank=True)
    item_buying_rate_record = models.ForeignKey('admin_management.InventoryItemBuyingRate',
                                                on_delete=models.SET_NULL, null=True, related_name='order_report')
    item_buying_rate = models.DecimalField(default=0, max_digits=16, decimal_places=2, null=True, blank=True)
    item_selling_rate_record = models.ForeignKey('admin_management.ClientItemSellingRate',
                                                 on_delete=models.SET_NULL, null=True, related_name='order_report')
    item_selling_rate = models.DecimalField(default=0, max_digits=16, decimal_places=2, null=True, blank=True)
    order_price = models.DecimalField(default=0, max_digits=16, decimal_places=2, null=True, blank=True)
    order_cost = models.DecimalField(default=0, max_digits=16, decimal_places=2, null=True, blank=True)
    expenses = models.DecimalField(default=0, max_digits=16, decimal_places=2, null=True, blank=True)
    marketeer_amount = models.DecimalField(default=0, max_digits=16, decimal_places=2, null=True, blank=True)
    order_investment_amount = models.DecimalField(default=0, max_digits=16, decimal_places=2, null=True, blank=True)
    profit = models.DecimalField(default=0, max_digits=16, decimal_places=2, null=True, blank=True)

    def __str__(self):
        return f'{self.client} | {self.item} | {self.delivery_date}'

    class Meta:
        ordering = ['-delivery_date']
        verbose_name = 'Order report'
        verbose_name_plural = 'Order reports'


class OrderContributionReport(BaseModel):
    order = models.ForeignKey('admin_management.Order', on_delete=models.SET_NULL, null=True,
                              related_name='order_contributor_report')
    contributor = models.ForeignKey('admin_management.Stakeholder', on_delete=models.SET_NULL, null=True)
    contributor_order_cost = models.DecimalField(default=0, max_digits=16, decimal_places=2, null=True, blank=True)
    contributor_expenses = models.DecimalField(default=0, max_digits=16, decimal_places=2, null=True, blank=True)
    contributor_investment_amount = models.DecimalField(default=0, max_digits=9, decimal_places=2, null=True,
                                                        blank=True)
    contributor_profit = models.DecimalField(default=0, max_digits=16, decimal_places=2, null=True, blank=True)

    def __str__(self):
        return f'{self.contributor.name}: {self.order}'

    class Meta:
        verbose_name = 'Contributor report'
        verbose_name_plural = 'Contributor reports'
        unique_together = ['order', 'contributor']

reporting_management/views.py
from django.http import Http404
from django.shortcuts import render
from django.views.generic import DetailView, ListView

from reporting_management.models import OrderReport, OrderContributionReport


def dashboard(request):
    report = OrderContributionReport.objects.filter(contributor_id=2).first()
    context = {
        'report': report
    }
    return render(request, 'reporting_management/dashboard.html', context)


class OrderReportListView(ListView):
    model = OrderReport


class OrderReportDetailView(DetailView):
    model = OrderReport


# def order_report(request):
#     context = {
#         'orders': OrderReport.objects.all()
#     }
#     return render(request, 'reporting_management/orderreport_list.html', context)

templates/reporting_management/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load number_extras %}

{% block page_content %}
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
    </div>

    <!-- Content Row -->
    <div class="row">

        <!-- Total Contributor's Purchases Card -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                Your Total Purchases
                            </div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">
                                Shs. {{ report.contributor_order_cost|round_dec|intcomma }}
                            </div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-comment-dollar fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Total Contributor's Expenses Card -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-success shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                Your Total Expenses
                            </div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">
                                Shs. {{ report.contributor_expenses|round_dec|intcomma }}
                            </div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-coins fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Total Contributor's Investment Card -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-info shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-info text-uppercase mb-1">
                                Your Total Investment
                            </div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">
                                Shs. {{ report.contributor_investment_amount|round_dec|intcomma }}
                            </div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-hand-holding-usd fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Total Contributor's Profit Card -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                                Your Total Profit
                            </div>
                            {% if report.contributor_profit > 0 %}
                                <div class="h5 mb-0 font-weight-bold text-gray-800">
                                    Shs. {{ report.contributor_profit|round_dec|intcomma }}
                                </div>
                            {% else %}
                                <div class="h5 mb-0 font-weight-bold text-danger">
                                    Shs. {{ report.contributor_profit|round_dec|intcomma }}
                                </div>
                            {% endif %}

                        </div>
                        <div class="col-auto">
                            <i class="fas fa-chart-line fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock page_content %}

templates/reporting_management/orderreport_detail.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load number_extras %}
{% load string_extras %}

{% block page_styles %}
    <!-- Custom styles for tables -->
    <link href="{% static 'core/vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
{% endblock page_styles %}

{% block page_content %}
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Reports</h1>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Orders Report</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>Item</th>
                        <th>Client</th>
                        <th>Quantity</th>
                        <th>Unit</th>
                        <th>{{ 'Delivery Date'|nbsp }}</th>
                        <th>{{ 'Order Status'|nbsp }}</th>
                        <th>{{ 'Payment Status'|nbsp }}</th>
                        <th>{{ 'Item Buying Rate'|nbsp }}</th>
                        <th>{{ 'Item Selling Rate'|nbsp }}</th>
                        <th>{{ 'Expected Income'|nbsp }}</th>
                        <th>{{ 'Order Cost'|nbsp }}</th>
                        <th>{{ 'Expenses'|nbsp }}</th>
                        <th>{{ 'Total Contribution'|nbsp }}</th>
                        <th>{{ "Marketeer\'s Amount"|nbsp }}</th>
                        <th>{{ 'Order Profit'|nbsp }}</th>
                    </tr>
                    </thead>
                    <tfoot>
                    <tr>
                        <th>Item</th>
                        <th>Client</th>
                        <th>Quantity</th>
                        <th>Unit</th>
                        <th>{{ 'Delivery Date'|nbsp }}</th>
                        <th>{{ 'Order Status'|nbsp }}</th>
                        <th>{{ 'Payment Status'|nbsp }}</th>
                        <th>{{ 'Item Buying Rate'|nbsp }}</th>
                        <th>{{ 'Item Selling Rate'|nbsp }}</th>
                        <th>{{ 'Expected Income'|nbsp }}</th>
                        <th>{{ 'Order Cost'|nbsp }}</th>
                        <th>{{ 'Expenses'|nbsp }}</th>
                        <th>{{ 'Total Contribution'|nbsp }}</th>
                        <th>{{ "Marketeer's Amount"|nbsp }}</th>
                        <th>{{ 'Order Profit'|nbsp }}</th>
                    </tr>
                    </tfoot>
                    <tbody>
                    {% for order in orderreport_list %}
                        <tr>
                            <td>{{ order.item|nbsp }}</td>
                            <td>{{ order.client|nbsp }}</td>
                            <td>{{ order.quantity }}</td>
                            <td>{{ order.unit }}</td>
                            <td>{{ order.delivery_date|naturalday|nbsp }}</td>
                            <td>{{ order.fulfilled }}</td>
                            <td>{{ order.payment_status }}</td>
                            <td>{{ order.item_buying_rate|round_dec|intcomma }}</td>
                            <td>{{ order.item_selling_rate|round_dec|intcomma }}</td>
                            <td>{{ order.order_price|round_dec|intcomma }}</td>
                            <td>{{ order.order_cost|round_dec|intcomma }}</td>
                            <td>{{ order.expenses|round_dec|intcomma }}</td>
                            <td>{{ order.order_investment_amount|round_dec|intcomma }}</td>
                            <td>{{ order.marketeer_amount|round_dec|intcomma }}</td>
                            <td>{{ order.profit|round_dec|intcomma }}</td>
                        </tr>
                    {% empty %}
                        <p>No orders data to display</p>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock page_content %}

{% block page_plugins %}
    <!-- Page level plugins -->
    <script src="{% static 'core/vendor/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'core/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
{% endblock page_plugins %}

{% block page_scripts %}
    <!-- Page level custom scripts -->
    <script src="{% static 'core/js/demo/datatables-demo.js' %}"></script>
{% endblock page_scripts %}

templates/reporting_management/orderreport_list.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load number_extras %}
{% load string_extras %}

{% block page_styles %}
    <!-- Custom styles for tables -->
    <link href="{% static 'core/vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
{% endblock page_styles %}

{% block page_content %}
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Reports</h1>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Orders Report</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>Item</th>
                        <th>Client</th>
                        <th>Quantity</th>
                        <th>Unit</th>
                        <th>{{ 'Delivery Date'|nbsp }}</th>
                        <th>{{ 'Order Status'|nbsp }}</th>
                        <th>{{ 'Payment Status'|nbsp }}</th>
                        <th>{{ 'Item Buying Rate'|nbsp }}</th>
                        <th>{{ 'Item Selling Rate'|nbsp }}</th>
                        <th>{{ 'Expected Income'|nbsp }}</th>
                        <th>{{ 'Order Cost'|nbsp }}</th>
                        <th>{{ 'Expenses'|nbsp }}</th>
                        <th>{{ 'Total Contribution'|nbsp }}</th>
                        <th>{{ "Marketeer\'s Amount"|nbsp }}</th>
                        <th>{{ 'Order Profit'|nbsp }}</th>
                    </tr>
                    </thead>
                    <tfoot>
                    <tr>
                        <th>Item</th>
                        <th>Client</th>
                        <th>Quantity</th>
                        <th>Unit</th>
                        <th>{{ 'Delivery Date'|nbsp }}</th>
                        <th>{{ 'Order Status'|nbsp }}</th>
                        <th>{{ 'Payment Status'|nbsp }}</th>
                        <th>{{ 'Item Buying Rate'|nbsp }}</th>
                        <th>{{ 'Item Selling Rate'|nbsp }}</th>
                        <th>{{ 'Expected Income'|nbsp }}</th>
                        <th>{{ 'Order Cost'|nbsp }}</th>
                        <th>{{ 'Expenses'|nbsp }}</th>
                        <th>{{ 'Total Contribution'|nbsp }}</th>
                        <th>{{ "Marketeer's Amount"|nbsp }}</th>
                        <th>{{ 'Order Profit'|nbsp }}</th>
                    </tr>
                    </tfoot>
                    <tbody>
                    {% for order in orderreport_list %}
                        <a href="{% url 'reporting_management:order-report-detail' pk=order.pk %}">
                            <tr>
                                <td>{{ order.item|nbsp }}</td>
                                <td>{{ order.client|nbsp }}</td>
                                <td>{{ order.quantity }}</td>
                                <td>{{ order.unit }}</td>
                                <td>{{ order.delivery_date|naturalday|nbsp }}</td>
                                <td>{{ order.fulfilled }}</td>
                                <td>{{ order.payment_status }}</td>
                                <td>{{ order.item_buying_rate|round_dec|intcomma }}</td>
                                <td>{{ order.item_selling_rate|round_dec|intcomma }}</td>
                                <td>{{ order.order_price|round_dec|intcomma }}</td>
                                <td>{{ order.order_cost|round_dec|intcomma }}</td>
                                <td>{{ order.expenses|round_dec|intcomma }}</td>
                                <td>{{ order.order_investment_amount|round_dec|intcomma }}</td>
                                <td>{{ order.marketeer_amount|round_dec|intcomma }}</td>
                                <td>{{ order.profit|round_dec|intcomma }}</td>
                            </tr>
                        </a>
                    {% empty %}
                        <p>No orders data to display</p>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock page_content %}

{% block page_plugins %}
    <!-- Page level plugins -->
    <script src="{% static 'core/vendor/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'core/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
{% endblock page_plugins %}

{% block page_scripts %}
    <!-- Page level custom scripts -->
    <script src="{% static 'core/js/demo/datatables-demo.js' %}"></script>
{% endblock page_scripts %}